sudo: required
services:
    - docker
    
before_install:
# build all images
    - docker build -t deepakaggarwal/client-builder -f ./client/Dockerfile.dev  ./client
   
scripts:
# run tests
    - docker run -e CI=true deepakaggarwal/client-builder npm  test -- --coverage


after_success:
# deploy all images to docker hub and dockerrun to aws
    - docker build -t deepakaggarwal/multi-docker-client ./client
    - docker build -t deepakaggarwal/multi-docker-server ./server
    - docker build -t deepakaggarwal/multi-docker-nginx ./nginx
    - docker build -t deepakaggarwal/multi-docker-worker ./worker
# log-in to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push the images
    - docker push deepakaggarwal/multi-docker-client
    - docker push deepakaggarwal/multi-docker-server
    - docker push deepakaggarwal/multi-docker-nginx 
    - docker push deepakaggarwal/multi-docker-worker
    